name: Compute Leaderboards

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy

      - name: Run compute script
        run: python compute/compute_rtg.py

      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/leaderboard_*.csv
          git commit -m "Auto-update leaderboards [skip ci]" || echo "No leaderboard changes"
          git fetch origin main
          git pull --rebase origin main
          git push origin main