name: Compute ACAC Ratings

on:
  push:
    paths:
      - "data/boxscores/**"
      - "compute/**"
      - ".github/workflows/compute-leaderboard.yml"

jobs:
  compute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy

      - name: Run compute script
        run: python compute/compute_rtg.py

      - name: Commit results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/leaderboard_*.csv
          git commit -m "Auto-update leaderboards [skip ci]" || echo "No changes to commit"
          git pull --rebase
          git push origin main
          
